public class Prog1
{ 
				int a = 10;
				int b = 20;
				public static void main(String[] args) //main method
				{
								
      Prog1 t = new Prog1();
      System.out.println("To Add a,b in Prog1"+ t.a);
						System.out.println("To Add a,b in Prog1"+ t.b);
						t.A();
						t.B();
				}
				
				
	void A()
		{
				
      System.out.println("To Add a,b in A"+ a);
      System.out.println("To Add a,b in A"+ b);
		}
				
	void B()
		{
				int a = 1000;
						int b = 2000;
      System.out.println("To Add a,b in B"+ a+b);
		}
				
}